### ISSUE TITLE
test with WordPress 4.2

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oer#13]
I heard reports from another developer that the latest WP update changes the way it handles taxonomies, likely breaking this plugin and maybe some others we have. Please test it on WP 4.2 and report back any issues or workarounds.

**Comment by joehobson** [comment]
info on the taxonomy shift: https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/

**Comment by johnpaulbalagolan** [comment]
thanks for the info
