### ISSUE TITLE
xvfb usage as a setting

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oer#17]
I found the problem with screenshots on our test server... xvfb is commented out in resources-importer.php (and init, but i covered that in #16). Please add an option in the Settings for "use xvfb" and only include these params in the array if it's on...

```
'xvfb-run',
'--auto-servernum',
'--server-num=1',
```

make sense? I know I have to turn it off when i'm developing and turn it on for the server, probably due to the Mac vs Ubuntu environment change

You could also separate the Settings page so that the screenshot settings are grouped in a fieldset separate from the other settings.

**Comment by johnpaulbalagolan** [comment]
fixed #19 with the latest code committed to github
