### ISSUE TITLE
add a static variable for $version - display it on settings

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oer#18]
I'd like to try out a new method for tracking and displaying the plugin version number. It's mainly needed on other OET plugins where we can't directly see the version number on the main WP Admin Plugins page, but need to know what version of our plugin is deployed. Could be helpful here as well.

I noticed how the Boonstra Slideshow plugin did it with this commit (bottom of the page):
https://github.com/Boonstra/Slideshow/commit/783328da2b28d90cb8104600861e29bbb0a7f746

That way we update it on the main script at the top in comments and in the variable, and then it's the same throughout the plugin.

Then add a footer to the Settings page displaying the plugin name and version and a link to more info - http://navigationnorth.com/wordpress/oer-management

**Comment by johnpaulbalagolan** [comment]
fixed #18 with the latest source committed to github but implemented this differently. please check if that would work.

Thanks.
