### ISSUE TITLE
Resources archive

### ISSUE THREAD

**Issue by marbaque** [navnorth/wp-oer#22]
I was trying to use this plugin and when I click on View all resources link, I get a white screen. 
The url I get is for the archive page is 'mysite.com/resource/'

I disabled all the other plugins, but the problem still remains.

**Comment by marbaque** [comment]
Thank you, I'll stay tuned 😉

Cheers,
Mario

**Comment by marbaque** [comment]
Thank you Joe,

What is the chance to have this plugin ready for translation? I'd like to
contribute to translate it to spanish, if it is possible.

Best

__

*Mario Badilla*
tel +506 8325-8362
web mariobadilla.com

**Comment by joehobson** [comment]
@marbaque the plugin is ready for translation but we don't have an ES translation file yet. I'll have @johnpaulbalagolan start one so you can see what format to contribute in. Would really appreciate your help on this, thanks

**Comment by joehobson** [comment]
@marbaque we started the ES translation file (here: https://github.com/navnorth/wp-oer/blob/master/lang/open-educational-resource-es_ES.po). All you have to do contribute is update the msgstr line for each string with the proper translation. If you want to see it in action on your local environment as you go, I think you have to generate the .mo binary file from your .po 

You can find more info about it on the WP developer site: https://developer.wordpress.org/plugins/internationalization/localization/
