### ISSUE TITLE
move readme.txt into ReadMe.md

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oer#6]
merge the readme.txt text into README.md so we have just one file

outline any additional steps for setting up the plugin based on your testing

**Comment by johnpaulbalagolan** [comment]
Done merging this. Thanks.

**Comment by joehobson** [comment]
go ahead and close issues when you finish them and if you put the issue number in the git commit (e.g. "fixing #6" then it will make it easier to connect the two.
