### ISSUE TITLE
check for XSS vulnerabilities

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oer#8]
this should be a fairly simple check since there aren't really any places where user input is displayed on the screen (other than basic WP search), but it would be good to learn what to look out for and ways to test for vulnerabilities.

**Comment by johnpaulbalagolan** [comment]
I have finished XSS vulnerability checking. But I am still checking for other ways to test for this type of vulnerabilities. Also checked for the suggestion of sucuri here, https://blog.sucuri.net/2015/04/security-advisory-xss-vulnerability-affecting-multiple-wordpress-plugins.html. Our plugin is not vulnerable.

**Comment by johnpaulbalagolan** [comment]
I have also done the following tests for XSS vulnerabilities in WP OER Plugin. I have found no XSS vulnerabilities.

- cross-site execution “><script src=http://idash.net/xs.js></script> as suggested here, http://janne.is/2013/02/testing-basic-xss/
- tried also adding autofocus and formaction on buttons as suggested here, http://html5sec.org/
- tested also setting src attribute of image to javascript alert like this, <IMG SRC=javascript:alert("XSS")>

fixed #8.
