### ISSUE TITLE
Date import and display

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oer#9]
Date’s do not seem to be displaying correctly, or maybe are not imported correctly from the spreadsheet. Should be displayed as MM/DD/YYYY

Would also be nice if there was some data validation when adding/editing/importing resources. For now, if the data submitted is not a date, leave it null on the resource.

**Comment by johnpaulbalagolan** [comment]
The dates are not imported correctly and found a bug that when there's no date specified for certain records in the import file, it will carry the date it previously processed instead of just null.

Should I create a new issue for it? or include this on this issue?

**Comment by joehobson** [comment]
nice catch. just include it on this issue, make note in the commit message.

**Comment by johnpaulbalagolan** [comment]
fixed #9. Also fixed the bug I mentioned above if there's no date in a record, it will be null instead of using the date from the previous record.
